describe('Verify Checkout Functionality', () => {
    it('Success Checkout', () => {
        cy.visit('https://www.saucedemo.com/')
        cy.get('#user-name').type('standard_user')
        cy.get('[data-test="password"]').type('secret_sauce')
        cy.get('.submit-button.btn_action').click()
        cy.url().should('include', '/inventory.html')
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('[data-test="remove-sauce-labs-backpack"]').should('be.visible')
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.get('[data-test="remove-sauce-labs-backpack"]').should('be.visible')
        cy.get('.shopping_cart_link').should('contain.text','2')
        cy.get('.shopping_cart_link').click()
        cy.url().should('include', '/cart.html')
        cy.get('[data-test="checkout"]').click()
        cy.url().should('include', '/checkout-step-one.html')
        cy.get('[data-test="firstName"]').type('elvanisa')
        cy.get('[data-test="lastName"]').type('muhsina')
        cy.get('[data-test="postalCode"]').type('1234')
        cy.get('[data-test="continue"]').click()
        cy.url().should('include', '/checkout-step-two.html')
        cy.get('[data-test="finish"]').click()
    })
  })